language: node_js
node_js:
- '0.11'
- '0.10'
env:
  matrix:
    secure: q4cn2rHpxQ8QMnF6Pafp9LZPidN3wQuwlapT19dEL73wcq/IeBrFka97LcS3ZoKYGA8oM7Pt0lU9HlkbSnIUOEE+QIo+RWcNVZtaTs4aRbXlOrvaAuCk5o+/s664ETdAnfHToA6RjzhqDcmFpDp7SOZki9XBOCDGJQIiOuzeQEM=
